from csv_utilities import make
from csv_utilities import find
from csv_utilities import add
from csv_utilities import read
from templates import template
from bs4 import BeautifulSoup

BeautifulSoup = BeautifulSoup()
make = make()
find = find()
add = add()
read = read()
template = template()

test_data = '''[['Gender', 'Deaths', 'Population', 'Crude Rate Per Capita'], ['Female', '22,569,507', '2,763,843,870', '816.6'], ['Male', '22,345,559', '2,671,902,519', '836.3']]'''

tree = make.xml_tree(read.file('../API-Responses/D140_All_Homicides_By_Year.xml'))

# Search the tree for the table generated by the query parameters
data_table = tree.find_all('r')

'''gender_cell = find.cell(each_row, 'c[l]', 0, 'l')
race_cell = find.cell(each_row, 'c[l]', 1, 'l')
year_cell = find.cell(each_row, 'c[l]', 2, 'l')
deaths_cell = find.cell(each_row, 'c[v]', 0, 'v')
pop_cell = find.cell(each_row, 'c[v]', 1, 'v')
crude_rate_cell = find.cell(each_row, 'c[v]', 2, 'v')'''


data_table_2 = data_table[2]
#print(data_table_2.select('c')[0]['l'])
read.table_data(data_table)
# Use with tree.find('r')
#print(data_table.select('c[l]')[0]['l'])

